const characters = [
  {
    id: 1,
    name: '36AIS',
    tier: 'SS',
    weapon: 'Staff',
    attribute: 'Healing',
    species: 'Oxsecian',
    lambdaForm: null,
    originalForm: null,
  },
  {
    id: 2,
    name: '54B2',
    tier: 'Z',
    weapon: 'Sword',
    attribute: null,
    species: 'Oxsecian',
    lambdaForm: null,
    originalForm: null,
  },
  {
    id: 3,
    name: "A'merpact",
    tier: 'A',
    weapon: 'Staff',
    attribute: 'Ice',
    species: 'Lizardfolk',
    lambdaForm: 4,
    originalForm: null,
  },
  {
    id: 4,
    name: "A'merpact ^",
    tier: 'SS',
    weapon: 'Staff',
    attribute: 'Ice',
    species: 'Lizardfolk',
    lambdaForm: null,
    originalForm: 3,
  },
  {
    id: 5,
    name: "A'misandra",
    tier: 'SS',
    weapon: 'Staff',
    attribute: 'Healing',
    species: 'Lizardfolk',
    lambdaForm: 6,
    originalForm: null,
  },
  {
    id: 6,
    name: "A'misandra ^",
    tier: 'Z',
    weapon: 'Staff',
    attribute: 'Healing',
    species: 'Lizardfolk',
    lambdaForm: null,
    originalForm: 5,
  },
  {
    id: 7,
    name: 'Alika',
    tier: 'S',
    weapon: 'Bow',
    attribute: 'Lightning',
    species: 'Human',
    lambdaForm: 8,
    originalForm: null,
  },
  {
    id: 8,
    name: 'Alika ^',
    tier: 'Z',
    weapon: 'Sword',
    attribute: 'Lightning',
    species: 'Human',
    lambdaForm: null,
    originalForm: 7,
  },
  {
    id: 9,
    name: 'Amazora',
    tier: 'B',
    weapon: 'Sword',
    attribute: 'Fire',
    species: 'Human',
    lambdaForm: 10,
    originalForm: null,
  },
  {
    id: 10,
    name: 'Amazora ^',
    tier: 'Z',
    weapon: 'Sword',
    attribute: 'Fire',
    species: 'Human',
    lambdaForm: null,
    originalForm: 9,
  },
];
export default characters;
