select 1;
SELECT 1;
Select 1;
selECT 1;
create database wild;
show databases;
use wild;
create database films;
use films;
show databases;
use wild;
create table student (id INT, firstname VARCHAR(100), lastname VARCHAR(150), birthdate DATE);
use films
create table movies(id int, title varchar(100), genre varchar(100));
show tables;
drop table movies;
show tables;
create table movie(id int, title varchar(100), genre varchar(100));
show tables;
use wild;
insert into student(id, firstname, lastname, birthdate) values(0,'Bob', 'Smith','1984-01-22');
select * from student;
select firstname from student;
select firstname, lastname from student where firstname='Bob';
select firstname, lastname from student where firstname='Arthur';
select firstname, lastname from student where firstname='bob';
select firstname, lastname from student where birthdate > '1990-01-01';
select firstname as prenom, lastname as nomDeFamille from student where birthdate > '1980-01-01';
use films;
describe movie;
insert into movie(id,title,genre) values (1,"Batman the Dark Knight","Action"), (2,"Dogma","Parody"), (3,"Tucker & Dale vs Evil","Parody"), (4, "Friendship is Magic", "Animation"), (5, "Gladiator", "Action");
select * from movie;
select title from movie;
select * from movie where title='Batman the Dark Knight';
select * from movie where genre="Action";